# Generated by Django 2.0 on 2018-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eid', models.IntegerField()),
                ('e_department', models.CharField(max_length=50)),
                ('e_post', models.CharField(max_length=50)),
                ('e_address', models.CharField(max_length=50)),
            ],
        ),
    ]
