# Generated by Django 2.0 on 2018-12-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_rollno', models.IntegerField()),
                ('st_address', models.CharField(max_length=50)),
                ('st_standard', models.CharField(max_length=10)),
            ],
        ),
    ]
