# Generated by Django 2.0 on 2018-12-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_standard',
            new_name='st_qualification',
        ),
    ]
